# Generated by Django 2.0.7 on 2018-07-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('split_wise', '0002_auto_20180725_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
