# Generated by Django 2.1 on 2018-09-09 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split_wise', '0003_bill_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(0, 'admin'), (1, 'member')], max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships',
                                            to='split_wise.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=16)),
                ('direction', models.CharField(choices=[(0, '+'), (1, '-')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='debt',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='owed_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions',
                                    to='split_wise.Bill'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
