# Generated by Django 2.1 on 2018-09-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('split_wise', '0004_auto_20180909_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills',
                                    to='split_wise.Group'),
        ),
    ]
