# Generated by Django 2.1 on 2018-09-10 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('split_wise', '0006_auto_20180909_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='bill_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
